# Install LDAP Packages
- name: Install OpenLDAP packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: 
  - openldap
  - openldap-servers
  - openldap-clients
    
- name: Configure root DN (olcSuffix + rootdn + rootpw)
  ansible.builtin.template:
    src: configure-rootdn.ldif.j2
    dest: /tmp/configure-rootdn.ldif
    mode: '0644'

- name: Apply root DN config to slapd (ldapmodify via ldapi:///)
  ansible.builtin.command:
    cmd: ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/configure-rootdn.ldif
  ignore_errors: true
  notify: Restart slapd

- name: Ensure slapd is restarted before adding base DN
  ansible.builtin.service:
    name: slapd
    state: restarted

- name: Deploy base DN LDIF (dc=hadoop,dc=test)
  ansible.builtin.template:
    src: basedn.ldif.j2
    dest: /tmp/basedn.ldif
    mode: '0644'

- name: Apply base DN (actually add entry into LDAP database)
  ansible.builtin.command:
    cmd: ldapadd -x -D "{{ ldap_rootdn }}" -w "{{ ldap_rootpw }}" -f /tmp/basedn.ldif
  ignore_errors: true
  notify: Restart slapd

- name: Verify base DN exists (quick search)
  ansible.builtin.command:
    cmd: ldapsearch -x -D "{{ ldap_rootdn }}" -w "{{ ldap_rootpw }}" -b "{{ ldap_basedn }}" -LLL dn
  register: ldap_search_out
  failed_when: false
  changed_when: false