# Base DN of the directory
ldap_basedn: "dc=hadoop,dc=test"

# Root DN (LDAP administrator account)
ldap_rootdn: "cn=Manager,dc=hadoop,dc=test"

# Root password (plaintext - used for ldapadd bind)
ldap_rootpw: "admin123"

# Root password (hashed - used in OpenLDAP configuration)
# Generate with: slappasswd -s admin123
ldap_rootpw_hashed: "{SSHA}f3o9kD2rV2Bp5OdpZ8tC1K1mBnA4F+0z"
